import ResolutionFiniteBaseProperness
import ResolutionOldFixingContextProperness

/-!
# Orbit compression as the common properness mechanism

This module separates the standard finite-dynamics ingredient from the
Resolution-specific no-limit argument.

The key weakening is trajectory finiteness: a stage observer need not have a
finite carrier.  It is enough that the single observer orbit generated by the
chosen unary syntactic family admits a uniform finite code.  This captures
both the finite-base theorem (where the whole observer is finite) and the
old-fixing theorem (where the base may be infinite but the relevant orbit has
a finite quotient).
-/

universe u v

namespace Resolution
namespace OrbitCompression

open Resolution.External
open Resolution.Orbit

variable {Sigma : Signature.{u}}

/-- A finite code only for one deterministic trajectory.  Equal codes at
ordered times must reflect equality of the actual orbit states; no finiteness
assumption is imposed on states outside this trajectory. -/
structure TrajectoryCoded
    {S : Type u} (g : S -> S) (s0 : S) (N : Nat) where
  code : Nat -> Nat
  code_lt : forall k : Nat, code k < N
  code_reflects : forall {i j : Nat}, i <= j -> code i = code j ->
    orb g s0 i = orb g s0 j

/-- A trajectory with `N` codes repeats within its first `N+1` positions. -/
theorem trajectory_repeat
    {S : Type u} {g : S -> S} {s0 : S} {N : Nat}
    (C : TrajectoryCoded g s0 N) :
    exists i j : Nat, i < j ∧ j <= N ∧ orb g s0 i = orb g s0 j := by
  have hb : forall i : Nat, i <= N -> C.code i < N := by
    intro i _
    exact C.code_lt i
  rcases Resolution.Pigeon.boundedRepeat N C.code hb with
    ⟨i, j, hij, hjN, heq⟩
  exact ⟨i, j, hij, hjN,
    C.code_reflects (Nat.le_of_lt hij) heq⟩

/-- The standard factorial-periodicity argument only needs a finite code of
this trajectory, not a finite code of the entire state space. -/
theorem orbit_eq_of_trajectory_factorial_dvd
    {S : Type u} {g : S -> S} {s0 : S} {N : Nat}
    (C : TrajectoryCoded g s0 N)
    {i j : Nat} (hi : N <= i) (hij : i <= j)
    (hdvd : fact N ∣ (j - i)) :
    orb g s0 i = orb g s0 j := by
  rcases trajectory_repeat C with ⟨a, b, hab, hbN, hEq⟩
  have hp : 0 < b - a := by omega
  have hpN : b - a <= N := by omega
  have hper : orb g s0 (a + (b - a)) = orb g s0 a := by
    rw [show a + (b - a) = b from by omega]
    exact hEq.symm
  rcases hdvd with ⟨c, hc⟩
  rcases dvd_fact N (b - a) hp hpN with ⟨d, hd⟩
  have hai : a <= i := by omega
  have hkey := orb_period_multiple g s0 hper (i - a) (c * d)
  rw [show a + (i - a) = i from by omega] at hkey
  have hmul : i + c * d * (b - a) = j := by
    have hstep : c * d * (b - a) = j - i := by
      rw [hc, hd]
      simp [Nat.mul_comm, Nat.mul_assoc]
    omega
  rw [hmul] at hkey
  exact hkey.symm

/-- A generated family whose interpretation in every finite-tag observer is a
deterministic orbit, with a uniform finite trajectory code at each stage. -/
structure ObserverOrbitCompression
    (D : PartialAlg.{u,v} Sigma) where
  term : Nat -> Free.GeneratedAns D
  step : forall {n : Nat}, FiniteTagAlg D n ->
    FiniteTagCarrier D n -> FiniteTagCarrier D n
  fold_orbit : forall {n : Nat} (T : FiniteTagAlg D n) (k : Nat),
    Free.TotalAlg.interp D (T.toTotalAlg D) (term k) =
      orb (step T)
        (Free.TotalAlg.interp D (T.toTotalAlg D) (term 0)) k
  bound : Nat -> Nat
  compressed : forall (n : Nat) (T : FiniteTagAlg D n),
    TrajectoryCoded (step T)
      (Free.TotalAlg.interp D (T.toTotalAlg D) (term 0)) (bound n)

/-- Factorial sampling of a compressed generated orbit. -/
def factorialSample
    {D : PartialAlg.{u,v} Sigma}
    (W : ObserverOrbitCompression D) (k : Nat) : Free.GeneratedAns D :=
  W.term (fact k)

theorem dvd_sub_of_dvd_of_dvd
    {d i j : Nat} (hi : d ∣ i) (hj : d ∣ j) : d ∣ (j - i) := by
  rcases hi with ⟨p, hp⟩
  rcases hj with ⟨q, hq⟩
  exact ⟨q - p, by rw [hp, hq, Nat.mul_sub_left_distrib]⟩

/-- Uniform finite trajectory compression implies factorial agreement at every
fixed observational stage. -/
theorem factorialSample_eqAt
    {D : PartialAlg.{u,v} Sigma}
    (W : ObserverOrbitCompression D)
    {n i j : Nat}
    (hi : W.bound n <= i) (hj : W.bound n <= j) :
    FiniteTagEqAt D n (factorialSample W i) (factorialSample W j) := by
  intro T
  change Free.TotalAlg.interp D (T.toTotalAlg D) (W.term (fact i)) =
    Free.TotalAlg.interp D (T.toTotalAlg D) (W.term (fact j))
  rw [W.fold_orbit T (fact i), W.fold_orbit T (fact j)]
  have hdi : fact (W.bound n) ∣ fact i :=
    fact_dvd_fact _ _ hi
  have hdj : fact (W.bound n) ∣ fact j :=
    fact_dvd_fact _ _ hj
  have hbi : W.bound n <= fact i :=
    Nat.le_trans hi (le_fact i)
  have hbj : W.bound n <= fact j :=
    Nat.le_trans hj (le_fact j)
  rcases Nat.le_total (fact i) (fact j) with hle | hle
  · exact orbit_eq_of_trajectory_factorial_dvd
      (W.compressed n T) hbi hle
      (dvd_sub_of_dvd_of_dvd hdi hdj)
  · exact (orbit_eq_of_trajectory_factorial_dvd
      (W.compressed n T) hbj hle
      (dvd_sub_of_dvd_of_dvd hdj hdi)).symm

/-- The abstract Cauchy half of Master II. -/
theorem factorialSample_cauchy
    {D : PartialAlg.{u,v} Sigma}
    (W : ObserverOrbitCompression D) :
    Filtered.Cauchy (generatedFilteredSpace D) (factorialSample W) := by
  intro n
  exact ⟨W.bound n, fun i j hi hj => factorialSample_eqAt W hi hj⟩

/-- No-limit is deliberately kept separate from orbit compression.  This is
where the Resolution-specific selected-pattern/overflow argument enters. -/
def NoGeneratedLimit
    {D : PartialAlg.{u,v} Sigma}
    (W : ObserverOrbitCompression D) : Prop :=
  forall x : Free.GeneratedAns D,
    ¬ Filtered.Converges (generatedFilteredSpace D) (factorialSample W) x

/-- Compression plus a Resolution-specific no-limit witness forces
incompleteness. -/
theorem notComplete_of_compression
    {D : PartialAlg.{u,v} Sigma}
    (W : ObserverOrbitCompression D)
    (hNo : NoGeneratedLimit W) :
    ¬ Filtered.Complete (generatedFilteredSpace D) := by
  intro hComplete
  rcases hComplete (factorialSample W) (factorialSample_cauchy W) with
    ⟨x, hx⟩
  exact hNo x hx

/-- Equivalently, the canonical completion embedding is not surjective. -/
theorem embeddingNotSurjective_of_compression
    {D : PartialAlg.{u,v} Sigma}
    (W : ObserverOrbitCompression D)
    (hNo : NoGeneratedLimit W) :
    ¬ Function.Surjective (Filtered.embed (generatedFilteredSpace D)) := by
  intro hSurj
  apply notComplete_of_compression W hNo
  exact (Filtered.complete_iff_embed_surjective
    (generatedFilteredSpace D)).2 hSurj

/-! ## Finite-base instance -/

noncomputable def finiteBaseCompression
    (D : PartialAlg.{u,v} Sigma)
    (f : Sigma.Op) (a z : D.Carrier)
    {baseSize : Nat}
    (C : Coded D.Carrier baseSize)
    (hUndefined : D.eval f a z = none) :
    ObserverOrbitCompression D where
  term := Resolution.Probe.comb D f a z
  step := fun {_} T => Resolution.FiniteBaseProperness.observerStep D f z T
  fold_orbit := by
    intro n T k
    exact Resolution.FiniteBaseProperness.foldComb_eq_orbit
      D f a z hUndefined T k
  bound := fun n => baseSize + n + 1
  compressed := by
    intro n T
    refine {
      code := fun k => Resolution.FiniteBaseProperness.finiteTagCode D C
        (orb (Resolution.FiniteBaseProperness.observerStep D f z T)
          (Resolution.FiniteBaseProperness.basePoint D a) k)
      code_lt := ?_
      code_reflects := ?_
    }
    · intro k
      exact Resolution.FiniteBaseProperness.finiteTagCode_lt D C _
    · intro i j hij hcode
      exact Resolution.FiniteBaseProperness.finiteTagCode_inj D C _ _ hcode

/-- The existing finite-base factorial Cauchy theorem is an instance of the
trajectory-compression master theorem. -/
theorem finiteBase_factorialCauchy_via_compression
    (D : PartialAlg.{u,v} Sigma)
    (f : Sigma.Op) (a z : D.Carrier)
    {baseSize : Nat}
    (C : Coded D.Carrier baseSize)
    (hUndefined : D.eval f a z = none) :
    Filtered.Cauchy (generatedFilteredSpace D)
      (Resolution.FiniteBaseProperness.factorialCombs D f a z) := by
  exact factorialSample_cauchy
    (finiteBaseCompression D f a z C hUndefined)

/-- The finite-base properness direction also factors through Master II. -/
theorem finiteBase_notComplete_via_compression
    (D : PartialAlg.{u,v} Sigma)
    (f : Sigma.Op) (a z : D.Carrier)
    {baseSize : Nat}
    (C : Coded D.Carrier baseSize)
    (hUndefined : D.eval f a z = none) :
    ¬ Filtered.Complete (generatedFilteredSpace D) := by
  apply notComplete_of_compression
    (finiteBaseCompression D f a z C hUndefined)
  intro x
  exact Resolution.FiniteBaseProperness.factorialCombs_noLimit
    D f a z hUndefined x

/-! ## Old-fixing infinite-base instance -/

noncomputable def oldFixingCompression
    (D : PartialAlg.{u,v} Sigma)
    (W : OldFixingContextWitness D) :
    ObserverOrbitCompression D where
  term := Resolution.OldFixingContextProperness.iterateAnswer D W
  step := fun {_} T => Resolution.OldFixingContextProperness.observerStep D W T
  fold_orbit := by
    intro n T k
    exact Resolution.OldFixingContextProperness.fold_iterate_eq_orbit D W T k
  bound := fun n => n + 2
  compressed := by
    intro n T
    let s0 := Free.TotalAlg.interp D (T.toTotalAlg D)
      (Resolution.OldFixingContextProperness.iterateAnswer D W 0)
    refine {
      code := fun k => tagCode
        (Resolution.OldFixingContextProperness.collapse D
          (orb (Resolution.OldFixingContextProperness.observerStep D W T)
            s0 k))
      code_lt := ?_
      code_reflects := ?_
    }
    · intro k
      exact tagCode_lt _
    · intro i j hij hcode
      have hc :
          Resolution.OldFixingContextProperness.collapse D
              (orb (Resolution.OldFixingContextProperness.observerStep D W T)
                s0 i) =
            Resolution.OldFixingContextProperness.collapse D
              (orb (Resolution.OldFixingContextProperness.observerStep D W T)
                s0 j) :=
        tagCode_inj _ _ hcode
      exact Resolution.OldFixingContextProperness.observerOrbit_eq_of_collapse_eq
        D W T s0 hij hc

/-- The old-fixing factorial Cauchy theorem is the same abstract compression
argument, despite the possibly infinite old carrier. -/
theorem oldFixing_factorialCauchy_via_compression
    (D : PartialAlg.{u,v} Sigma)
    (W : OldFixingContextWitness D) :
    Filtered.Cauchy (generatedFilteredSpace D)
      (Resolution.OldFixingContextProperness.factorialIterates D W) := by
  exact factorialSample_cauchy (oldFixingCompression D W)

/-- The old-fixing properness theorem also factors through Master II; its
no-limit half remains the selected-prefix/absorbing-overflow argument. -/
theorem oldFixing_notComplete_via_compression
    (D : PartialAlg.{u,v} Sigma)
    (W : OldFixingContextWitness D) :
    ¬ Filtered.Complete (generatedFilteredSpace D) := by
  apply notComplete_of_compression (oldFixingCompression D W)
  intro x
  exact Resolution.OldFixingContextProperness.factorialIterates_noLimit D W x

end OrbitCompression
end Resolution
