import ResolutionStrongTotalityKernelBridge
import ResolutionFreeCompletionFinal

/-!
# Free algebra bridge for Strong Totality

The expression-level kernel bridge shows that one resolved expression can be
viewed as a structured Strong Totality answer.  This module lifts that fact to
the whole generated free answer type.

For a partial algebra `D`, define a specification whose ordinary candidates are
old carrier values and whose acceptance predicate says that the old value is
generated by some expression.  The residual vocabulary consists precisely of
generated suspension trees, including their complete `RawAns` provenance.

The resulting structured Strong Totality answer type is equivalent to
`Free.GeneratedAns D`.  Hence the pre-existing free Resolution algebra is not a
parallel construction: it is exactly a provenance-preserving Strong Totality
presentation of the generated-answer layer.

No global inhabitance claim is made for `GeneratedAns D`: if the old carrier is
empty, there need not be any closed expression to generate an answer.  Strong
Totality remains the statement about arbitrary well-formed specifications; the
free generated layer is identified here only when generated data exist.
-/

universe u v

namespace Resolution
namespace StrongTotality

variable {Sigma : Signature.{u}}

/-- An old carrier value is accepted when some expression resolves exactly to
that old value. -/
def generatedOldSpecification
    (D : PartialAlg.{u,v} Sigma) : Specification.{v} where
  Candidate := D.Carrier
  accepts := fun a =>
    Exists fun e : Expr Sigma D.Carrier => Expr.res D e = .old a

/-- A generated suspension, retaining the whole suspension node together with
proof that it is produced by an expression. -/
structure GeneratedSuspension
    (D : PartialAlg.{u,v} Sigma) : Type (max u v) where
  op : Sigma.Op
  left : RawAns Sigma D.Carrier
  right : RawAns Sigma D.Carrier
  generated : Exists fun e : Expr Sigma D.Carrier =>
    Expr.res D e = .susp op left right

namespace GeneratedSuspension

/-- Forget the decomposition witness and view a generated suspension as an
ordinary generated free answer. -/
def toGeneratedAns
    {D : PartialAlg.{u,v} Sigma}
    (r : GeneratedSuspension D) : Free.GeneratedAns D :=
  ⟨.susp r.op r.left r.right, r.generated⟩

/-- Forget only the generation proof and recover the native raw suspension. -/
def toRawAns
    {D : PartialAlg.{u,v} Sigma}
    (r : GeneratedSuspension D) : RawAns Sigma D.Carrier :=
  .susp r.op r.left r.right

end GeneratedSuspension

/-- The Strong Totality presentation of the generated free answer algebra. -/
abbrev GeneratedStrongAnswer
    (D : PartialAlg.{u,v} Sigma) : Type (max u v) :=
  ResolutionAnswerWith
    (generatedOldSpecification D)
    (GeneratedSuspension D)

/-- Every generated free answer canonically becomes either a realized generated
old value or a provenance-preserving generated suspension. -/
def generatedAnsToStrong
    (D : PartialAlg.{u,v} Sigma) :
    Free.GeneratedAns D -> GeneratedStrongAnswer D
  | ⟨.old a, hgen⟩ => .realized a hgen
  | ⟨.susp op left right, hgen⟩ =>
      .residual ⟨op, left, right, hgen⟩

/-- Decode a structured generated Strong Totality answer back to the existing
free generated answer type. -/
def strongToGeneratedAns
    (D : PartialAlg.{u,v} Sigma) :
    GeneratedStrongAnswer D -> Free.GeneratedAns D
  | .realized a hgen => ⟨.old a, hgen⟩
  | .residual r => r.toGeneratedAns

/-- Encoding then decoding a generated free answer is the identity. -/
@[simp] theorem strongToGeneratedAns_generatedAnsToStrong
    (D : PartialAlg.{u,v} Sigma)
    (x : Free.GeneratedAns D) :
    strongToGeneratedAns D (generatedAnsToStrong D x) = x := by
  cases x with
  | mk raw hgen =>
      cases raw <;> rfl

/-- Decoding then encoding a structured generated Strong Totality answer is the
identity. -/
@[simp] theorem generatedAnsToStrong_strongToGeneratedAns
    (D : PartialAlg.{u,v} Sigma)
    (a : GeneratedStrongAnswer D) :
    generatedAnsToStrong D (strongToGeneratedAns D a) = a := by
  cases a with
  | realized x hx => rfl
  | residual r =>
      cases r
      rfl

/-- The generated free Resolution algebra is exactly the structured Strong
Totality presentation obtained by separating generated old results from
generated suspension provenance. -/
def generatedAnsEquivStrong
    (D : PartialAlg.{u,v} Sigma) :
    Equiv (Free.GeneratedAns D) (GeneratedStrongAnswer D) where
  toFun := generatedAnsToStrong D
  invFun := strongToGeneratedAns D
  left_inv := strongToGeneratedAns_generatedAnsToStrong D
  right_inv := generatedAnsToStrong_strongToGeneratedAns D

/-- The equivalence preserves generated old values exactly. -/
@[simp] theorem generatedAnsEquivStrong_old
    (D : PartialAlg.{u,v} Sigma)
    (a : D.Carrier) :
    (generatedAnsEquivStrong D).toFun (Free.generatedOld D a) =
      (.realized a ⟨Expr.val a, rfl⟩ : GeneratedStrongAnswer D) := by
  rfl

/-- Every generated expression factors through the global Strong Totality/free
algebra equivalence. -/
theorem generatedAnsEquivStrong_ofExpr
    (D : PartialAlg.{u,v} Sigma)
    (e : Expr Sigma D.Carrier) :
    strongToGeneratedAns D
        (generatedAnsToStrong D (Free.ofExpr D e)) =
      Free.ofExpr D e := by
  exact strongToGeneratedAns_generatedAnsToStrong D (Free.ofExpr D e)

/-- A generated suspension is represented as a residual carrying exactly the
same native `RawAns` suspension tree. -/
theorem generatedAnsToStrong_of_susp
    (D : PartialAlg.{u,v} Sigma)
    (op : Sigma.Op)
    (left right : RawAns Sigma D.Carrier)
    (hgen : Exists fun e : Expr Sigma D.Carrier =>
      Expr.res D e = .susp op left right) :
    generatedAnsToStrong D
        (⟨.susp op left right, hgen⟩ : Free.GeneratedAns D) =
      (.residual ⟨op, left, right, hgen⟩ : GeneratedStrongAnswer D) := by
  rfl

/-- Coarsening the free algebra presentation forgets only suspension provenance:
generated old answers remain realized, while every generated suspension becomes
the unique minimal residual. -/
def generatedAnsToMinimal
    (D : PartialAlg.{u,v} Sigma) :
    Free.GeneratedAns D -> ResolutionAnswer (generatedOldSpecification D) :=
  fun x => coarsenResidual (generatedAnsToStrong D x)

@[simp] theorem generatedAnsToMinimal_old
    (D : PartialAlg.{u,v} Sigma)
    (a : D.Carrier) :
    generatedAnsToMinimal D (Free.generatedOld D a) =
      realizeSolution
        (⟨a, ⟨Expr.val a, rfl⟩⟩ :
          Specification.Solution (generatedOldSpecification D)) := by
  rfl

@[simp] theorem generatedAnsToMinimal_susp
    (D : PartialAlg.{u,v} Sigma)
    (op : Sigma.Op)
    (left right : RawAns Sigma D.Carrier)
    (hgen : Exists fun e : Expr Sigma D.Carrier =>
      Expr.res D e = .susp op left right) :
    generatedAnsToMinimal D
        (⟨.susp op left right, hgen⟩ : Free.GeneratedAns D) =
      (ResolutionAnswer.residual :
        ResolutionAnswer (generatedOldSpecification D)) := by
  rfl

end StrongTotality
end Resolution
